/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: simonecazzaniga (https://sketchfab.com/simonecazzaniga)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/city-deb4dc75e62346c19c117bf61334eeb5
Title: City
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
// import IslandScene from "../assets/3d/island.glb";
import { a } from "@react-spring/three";
const  City = (props) =>{
  const { nodes, materials } = useGLTF("/city.glb");
  const cityRef = useRef();
  return (
    <a.group {...props} ref={cityRef}  >
      <group
       
      >
        <mesh
          
          
          geometry={nodes.macchina020_materiale_base_0.geometry}
          material={materials.materiale_base}
        />
        <mesh
          
          
          geometry={nodes.macchina020_materiale_base_0_1.geometry}
          material={materials.materiale_base}
        />
      </group>
      <mesh
        
        
        geometry={nodes.cartello_P_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes.cartello_triangolo_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.divieto_rosso_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes.seemaforo001_materiale_base_0.geometry}
        material={materials.materiale_base}
     
      />
      <mesh
        
        
        geometry={nodes.seemaforo002_materiale_base_0.geometry}
        material={materials.materiale_base}
     
      />
      <mesh
        
        
        geometry={nodes.seemaforo003_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.seemaforo004_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.seemaforo005_materiale_base_0.geometry}
        material={materials.materiale_base}
    
      />
      <mesh
        
        
        geometry={nodes.seemaforo006_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.seemaforo007_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.seemaforo008_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.cartello_triangolo001_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes.cartello_triangolo002_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_triangolo003_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_P001_cartelli_0.geometry}
        material={materials.cartelli}
   
      />
      <mesh
        
        
        geometry={nodes.cartello_P002_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_P003_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione005_cartelli_0.geometry}
        material={materials.cartelli}
     
      />
      <mesh
        
        
        geometry={nodes.divieto_rosso001_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_P004_cartelli_0.geometry}
        material={materials.cartelli}
      
      />
      <mesh
        
        
        geometry={nodes.cartello_P005_cartelli_0.geometry}
        material={materials.cartelli}
        
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione001_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione003_cartelli_0.geometry}
        material={materials.cartelli}
    
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione006_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione009_cartelli_0.geometry}
        material={materials.cartelli}
     
      />
      <mesh
        
        
        geometry={nodes.cartello_direzione011_cartelli_0.geometry}
        material={materials.cartelli}
       
      />
      <mesh
        
        
        geometry={nodes["citt��_materiale_base_0"].geometry}
        material={materials.materiale_base}
        
      />
      <mesh
        
        
        geometry={nodes.camioncino_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.Cube018_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.base_casa_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.tenda001_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.Icosphere002_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.police_station_materiale_base_0.geometry}
        material={materials.materiale_base}
    
      />
      <mesh
        
        
        geometry={nodes.tenda002_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.base_casa001_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.casa003_materiale_base_0.geometry}
        material={materials.materiale_base}
 
      />
      <mesh
        
        
        geometry={nodes.cespuglio003_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.cespuglio007_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.cespuglio004_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.cespuglio005_materiale_base_0.geometry}
        material={materials.materiale_base}
    
      />
      <mesh
        
        
        geometry={nodes.cespuglio006_materiale_base_0.geometry}
        material={materials.materiale_base}
        position={[-1570.249, 40.532, 2031.609]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={81.43}
      />
      <mesh
        
        
        geometry={nodes.cespuglio009_materiale_base_0.geometry}
        material={materials.materiale_base}
        position={[-724.045, 40.532, 1691.194]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={81.461}
      />
      <mesh
        
        
        geometry={nodes.cespuglio010_materiale_base_0.geometry}
        material={materials.materiale_base}
        position={[-724.045, 40.532, 2038.605]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={81.461}
      />
      <mesh
        
        
        geometry={nodes.cespuglio008_materiale_base_0.geometry}
        material={materials.materiale_base}
        position={[13.846, 40.486, 1447.946]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={90.562}
      />
      <mesh
        
        
        geometry={nodes.Plane003_materiale_base_0.geometry}
        material={materials.materiale_base}
        position={[1270.251, 40.653, -782.345]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        
        
        geometry={nodes.Plane004_onlytexture003_0.geometry}
        material={materials["onlytexture.003"]}
       
      />
      <mesh
        
        
        geometry={nodes.Plane005_materiale_base_0.geometry}
        material={materials.materiale_base}

      />
      <mesh
        
        
        geometry={nodes.casa001_materiale_base_0.geometry}
        material={materials.materiale_base}
     
      />
      <mesh
        
        
        geometry={nodes.casa002_materiale_base_0.geometry}
        material={materials.materiale_base}
  
      />
      <mesh
        
        
        geometry={nodes.Cylinder_onlytexture004_0.geometry}
        material={materials["onlytexture.004"]}
     
      />
      <mesh
        
        
        geometry={nodes.Cylinder002_onlytexture004_0.geometry}
        material={materials["onlytexture.004"]}
 
      />
      <mesh
        
        
        geometry={nodes.Cube_materiale_base_0.geometry}
        material={materials.materiale_base}
 
      />
      <mesh
        
        
        geometry={nodes.Icosphere004_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.panchina004_materiale_base_0.geometry}
        material={materials.materiale_base}
      />
      <mesh
        
        
        geometry={nodes.Cylinder003_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.Cylinder001_texture004_0.geometry}
        material={materials["texture.004"]}
    
      />
      <mesh
        
        
        geometry={nodes.Sphere_materiale_base_0.geometry}
        material={materials.materiale_base}
 
      />
      <mesh
        
        
        geometry={nodes.pizzeria_materiale_base_0.geometry}
        material={materials.materiale_base}
    
      />
      <mesh
        
        
        geometry={nodes.Icosphere001_materiale_base_0.geometry}
        material={materials.materiale_base}
   
      />
      <mesh
        
        
        geometry={nodes.pizzeria001_mattoni_0.geometry}
        material={materials.mattoni}
    
      />
      <mesh
        
        
        geometry={nodes.ruote_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.Icosphere003_materiale_base_0.geometry}
        material={materials.materiale_base}
       
      />
      <mesh
        
        
        geometry={nodes.Icosphere005_materiale_base_0.geometry}
        material={materials.materiale_base}
     
      />
      <mesh
        
        
        geometry={nodes.tenda003_materiale_base_0.geometry}
        material={materials.materiale_base}
      
      />
      <mesh
        
        
        geometry={nodes.vetro_vetro_0.geometry}
        material={materials.vetro}
      
      />
      <mesh
        
        
        geometry={nodes.vetro001_vetro_0.geometry}
        material={materials.vetro}
        
      />
      <mesh
        
        
        geometry={nodes.vetro002_vetro_0.geometry}
        material={materials.vetro}
    
      />
      <mesh
        
        
        geometry={nodes.vetro003_vetro_0.geometry}
        material={materials.vetro}
      
      />
      <mesh
        
        
        geometry={nodes.vetro004_vetro_0.geometry}
        material={materials.vetro}
       
      />
      <mesh
        
        
        geometry={nodes.vetro008_vetro_0.geometry}
        material={materials.vetro}
    
      />
      <mesh
        
        
        geometry={nodes.vetro006_vetro_0.geometry}
        material={materials.vetro}
       
      />
      <mesh
        
        
        geometry={nodes.vetro007_vetro_0.geometry}
        material={materials.vetro}
      
      />
      <mesh
        
        
        geometry={nodes.vetro005_vetro_0.geometry}
        material={materials.vetro}
      
      />
      <mesh
        
        
        geometry={nodes.vetro009_vetro_0.geometry}
        material={materials.vetro}
     
      />
      <mesh
        
        
        geometry={nodes.vetro010_vetro_0.geometry}
        material={materials.vetro}
       
      />
    </a.group>
  );
}

export default City;
